import os
import time
from flask import Flask, render_template, request, send_file, after_this_request
import yt_dlp

app = Flask(__name__)

# Ensure a downloads directory exists
DOWNLOAD_FOLDER = 'downloads'
if not os.path.exists(DOWNLOAD_FOLDER):
    os.makedirs(DOWNLOAD_FOLDER)

def cleanup_file(filepath):
    """
    Deletes the file after it has been sent to the user to save server space.
    """
    try:
        if os.path.exists(filepath):
            os.remove(filepath)
    except Exception as e:
        print(f"Error deleting file: {e}")

@app.route('/', methods=['GET'])
def home():
    return render_template('index.html')

@app.route('/download', methods=['POST'])
def download():
    youtube_url = request.form.get('url')
    
    if not youtube_url:
        return "Error: No URL provided", 400

    # Configure yt-dlp
    # We use a unique timestamp in the filename to prevent conflicts between users
    timestamp = int(time.time())
    output_template = f'{DOWNLOAD_FOLDER}/audio_{timestamp}_%(title)s.%(ext)s'

    ydl_opts = {
        'format': 'bestaudio/best',
        'outtmpl': output_template,
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '192',
        }],
        'quiet': True,
        'noplaylist': True,
    }

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(youtube_url, download=True)
            # Retrieve the filename generated by yt-dlp (with the .mp3 extension)
            filename = ydl.prepare_filename(info)
            final_filename = os.path.splitext(filename)[0] + ".mp3"

        # Schedule file deletion after the response is sent
        @after_this_request
        def remove_file(response):
            cleanup_file(final_filename)
            return response

        # Send the file to the user's browser
        return send_file(final_filename, as_attachment=True)

    except Exception as e:
        return f"Error occurred: {str(e)}", 500

if __name__ == '__main__':
    # host='0.0.0.0' allows access from other computers on the same network
    app.run(debug=True, host='0.0.0.0', port=5000)